### ISSUE TITLE
Dashboard: Healthy miner power distribution

### ISSUE THREAD

**Issue by olizilla** [filecoin-project/sentinel#174]
A graph showing miner entities power distribution over time. Miners should be grouped by entities.

In order to show miner quality adjusted power per miner I think we need to backfill the `power_actor_claims` table, and keep it up to date. As this is a dashboard request, it should be available in the Sentinel Monitoring db.

To be able to group by entity rather than miner we will need to make the analysis schema available to the monitoring db as well.

### TODO

- [ ] Create dashboard - wip: https://protocollabs.grafana.net/d/gjkXD3hMk/sentinel-storage-power-consensus?orgId=1
- [ ] Add threshold and alert if a single group has over 33% of the total power
- [ ] Populate `power_actor_claims` back to genesis in the monitoring db
- [ ] Ensure `power_actor_claims` is updated live.

**Comment by olizilla** [comment]
I am working on the assumption that anything we want to alert on should be available in the monitoring db. The `power_actor_claims` table contains the Quality Adjusted Power score per miner only when it changes. To get an accurate picture of the network we need the table to contain a complete record from genesis, or we need a strategy for inserting roll-ups for that table.

**Comment by olizilla** [comment]
Do we need a better way to answer the distribution over time query? I suspect that for monitoring we really only care about the current power distribution and the trend over the last 7 days

**Comment by iand** [comment]
Backfilling data from genesis to 81k which should cover the gap
