### ISSUE TITLE
Bootstrap a server

### ISSUE THREAD

**Issue by kasteph** [filecoin-project/sentinel#238]
```[tasklist]
### Tasks
- [x] Evaluate between Flask, Litestar, and aiohttp
- [x] Create a web server that can be connected locally
- [x] Write a Dockerfile and compose file for local development
- [ ] Provision a compute instance and SQL db
- [ ] Create deployment pipeline to deploy to compute instance
- [ ] Write documentation on local setup and deployment
```

**Comment by birdychang** [comment]
web app framework comparison: https://github.com/filecoin-project/mercury-api/issues/2

**Comment by kasteph** [comment]
transferring tasks to #242
