### ISSUE TITLE
Configure basic endpoints

### ISSUE THREAD

**Issue by kasteph** [filecoin-project/sentinel#239]
```[tasklist]
### Tasks
- [x] Connect BigQuery as a backing datastore for the REST endpoints
- [x] POST /query with query body
- [x] Implement pagination to /query endpoint
- [x] Add bytes processed view on admin page for all users
- [ ] Add bytes processed in /stats for the user
- [ ] Generate OpenAPI schema with above endpoints
```

**Comment by kasteph** [comment]
Query estimation: https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/get

**Comment by kasteph** [comment]
Moving tasks to #242 for consolidation
