### ISSUE TITLE
Milestone: Migrate Grafana dashboards

### ISSUE THREAD

**Issue by kasteph** [filecoin-project/sentinel#264]
eta: 2023-12-31

description:
We need to move dashboards from the Protocol Labs account to the Sentinel account. Transferring should be straightforward (copy the JSON definition of each dashboard).

```[tasklist]
### Tasks
- [ ] connect Postgres and BigQuery data sources
- [ ] connect Grafana Agent data sources (for filcryo and data-platform)
- [ ] transfer Sentinel Alerts dashboard
- [ ] transfer Sentinel Ops dashboard
- [ ] transfer KPIs dashboard
- [ ] transfer network monitoring dashboard
```
