### ISSUE TITLE
Miner Sector Lifecycle Event Tracking (Post Refactor)

### ISSUE THREAD

**Issue by frrist** [filecoin-project/sentinel#29]
### Motivation
After the recent refactor of the miner actor we wish to track sector life cycle events. Below is an outline of each event, what it means, and how to track it via inspection of the miner actors state.

- [x] PreCommit Added: A PreCommit is added to miners PreCommit AMT
  - To Track: Inspect PreCommit AMT for change between two sequential epochs, anything added is a PreCommit Added event

- [x] PreCommit Expire: A PreCommit is removed from the miner PreCommitSector AMT and does not appear n a miners Sector AMT
  - To Track: Inspect PreCommit AMT for change between two sequential epochs, anything removed and does not exist in Sector AMT is PreCommit Expired event

- [x] Commit Added: A Sector (with Deals)  is added to a miners Sector AMT (from the PreCommit AMT)
  - To Track: Inspect Sector AMT for change between two sequential epochs, anything added is a Commit Added event.

- [x] Commit Capacity Added: A Sector with no deals (committed capacity sector) is added to a miners Sector AMT.
  - To Track: Inspect Sector AMT for change between two sequential epochs, anything added with no deals is a Commit Capacity Added event

- [x] Commit Extended: A Sector in a miners Sectors AMT has its Expiration Epoch value increased.
  - To Track: Inspect Sector AMT for change between two sequential epochs, anything Modified can be considered extended as that is the only allowed modification of SectorOnChainInfo

- [x] Commit Expire: A Sector is removed from a miners Sector AMT due to its expiration epoch passing.
  - To Track: Inspect Partitions ExpirationEpochs AMT for change between two sequential epochs. Any sector that appeared in the AMT at old epoch that does not exist in AMT at new epoch for any future epoch and was in the OnTimeSectors Bitfield of the ExpirationSet is considered expired.
- [x] Commit Fault: A Sector does not have a corresponding PoSt within its deadline.
  - To Track: Inspect Partitions Faults for change between two sequential epochs, anything added is considered Faulted

- [x] Commit In Recovery: A Sector in fault is scheduled by a miner to recover
  - To Track: Inspect Partitions Recoveries for change between two sequential epochs, anything added is considered In Recovery

- [x] Commit Recovered: A Sector is recovered when it has a successful PoSt submitted for it.
  - To Track: If a Sector is in Partitions#Sectors and not in Partitions#Faults+Partitions#Recoveries+Partitions#Terminated it has been recovered.

- [x] Commit Terminated: A Sector is terminated before its expiration epoch
  - To Track: A Sector appears in Partitions EarlyTerminated AMT
